pipeline {
    agent any

    options {
        disableConcurrentBuilds()
        timestamps()
    }

    stages {
        stage('Checkout depuis Git') {
            steps {
                checkout scm
                echo 'Code récupéré depuis GitHub.'
            }
        }

        stage('Verification du projet') {
            steps {
                bat 'dir'
                dir('achat') {
                    bat 'dir'
                }
            }
        }

        stage('Build Maven') {
            steps {
                dir('achat') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Tests avec JaCoCo') {
            steps {
                dir('achat') {
                    bat 'mvn test -DfailIfNoTests=false'
                }
            }
        }

        stage('Analyse SonarQube') {
            steps {
                dir('achat') {
                    echo 'Analyse de la qualite du code avec SonarQube...'
                    withSonarQubeEnv('SonarQube') {
                        bat '''
                            mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar ^
                            -Dsonar.projectKey=achat ^
                            -Dsonar.projectName=achat
                        '''
                    }
                }
            }
        }

        stage('Package') {
            steps {
                dir('achat') {
                    bat 'mvn package -DskipTests'
                }
            }
        }
    }

    post {
        success {
            echo 'Build terminé avec succès.'
        }

        failure {
            echo 'Build échoué.'
        }

        always {
            archiveArtifacts artifacts: 'achat/target/*.jar',
                             fingerprint: true,
                             allowEmptyArchive: true
        }
    }
}