
spring.datasource.url=jdbc:postgresql://postgres:5432/achatdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ?????????????????????????????????????????????????????????????
# SERVER
# ?????????????????????????????????????????????????????????????
server.port=8089

# ?????????????????????????????????????????????????????????????
# ACTUATOR ? Exposition des endpoints de monitoring
# ?????????????????????????????????????????????????????????????
management.endpoints.web.exposure.include=health,info,prometheus,metrics,loggers,env
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true

# Préfixe des métriques (affiché dans Grafana)
management.metrics.tags.application=${spring.application.name:achat-app}

# Métriques JVM activées
management.metrics.enable.jvm=true
management.metrics.enable.process=true
management.metrics.enable.system=true

# Métriques HikariCP (pool de connexions DB)
management.metrics.enable.hikaricp=true

# ?????????????????????????????????????????????????????????????
# LOGGING
# ?????????????????????????????????????????????????????????????
logging.level.root=INFO
logging.level.tn.esprit=DEBUG